#!/bin/bash
# /etc/init.d/gpio-joystick

### BEGIN INIT INFO
# Provides:          sunfounder
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: GPIO Joystick service
# Description:       This service is used to startup GPIO Joystick service
### END INIT INFO


case "$1" in
    start)
        echo "Starting gpio-joystick"
        sudo gpio-joystick 2>&1 1>/dev/null &
        ;;
    stop)
        echo "Stopping gpio-joystick"
        sudo kill $(ps aux | grep 'gpio-joystick' | awk '{ print $2 }')
        ;;
    *)
        echo "Usage: sudo service gpio-joystick start|stop|restart"
        exit 1
        ;;
esac

exit 0
